export enum ROUTES_ENUM {
  HOME = '/',
  POSTS = '/posts',
  AUTH = '/auth',
  LOG_IN = '/login',
  SIGN_UP = '/signup',
  USER = '/user',
  CODE_SANDBOX = '/codesandbox',
  TEXT_EDITOR = '/textEditor',
  POSTS_EDITOR = '/posts-editor',
  ERROR = '/error',
  USER_ACCOUNT = '/account',
  PRIVACY_POLICY = '/privacy-policy',
  ABOUT = '/about',
}
